-- Local Embeddings: 384-d pgvector table
--
-- Stores sentence-transformers embeddings for learning examples.
-- Dimension: 384 (all-MiniLM-L6-v2)
-- 
-- Records are privacy-safe (no PII, no RAG context).

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create table
CREATE TABLE IF NOT EXISTS learning_vectors_384_v1 (
  id TEXT PRIMARY KEY,
  example_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  embedding VECTOR(384) NOT NULL,
  schema_version TEXT NOT NULL DEFAULT 'signals_v1',
  source TEXT NOT NULL, -- 'mock' | 'real'
  industry_key TEXT NOT NULL,
  pii_scrubbed BOOLEAN NOT NULL DEFAULT TRUE,
  metadata JSONB
);

-- Indexes
CREATE INDEX IF NOT EXISTS learning_vectors_384_v1_example_id_idx 
  ON learning_vectors_384_v1 (example_id);

CREATE INDEX IF NOT EXISTS learning_vectors_384_v1_source_idx 
  ON learning_vectors_384_v1 (source);

CREATE INDEX IF NOT EXISTS learning_vectors_384_v1_industry_key_idx 
  ON learning_vectors_384_v1 (industry_key);

-- Vector similarity index (HNSW for fast approximate search)
CREATE INDEX IF NOT EXISTS learning_vectors_384_v1_embedding_idx 
  ON learning_vectors_384_v1 
  USING hnsw (embedding vector_cosine_ops);

-- Comments
COMMENT ON TABLE learning_vectors_384_v1 IS 
  'Local embeddings (384-d) for learning examples. Generated by sentence-transformers/all-MiniLM-L6-v2.';

COMMENT ON COLUMN learning_vectors_384_v1.embedding IS 
  '384-dimensional vector from sentence-transformers model';

COMMENT ON COLUMN learning_vectors_384_v1.pii_scrubbed IS 
  'TRUE if PII guards were applied before embedding (always true for signals_v1)';

COMMENT ON COLUMN learning_vectors_384_v1.metadata IS 
  'Optional metadata: boundary_class, pressure_keys, labels, etc.';
